import './style.css';
import { Sandbox } from './sandbox';
import { scenes } from './scenes';
import { loadPreferences, parseExperiment, savePreferences } from './storage';

document.querySelector<HTMLDivElement>('#app')!.innerHTML = `
<main class="game-shell">
  <header class="topbar"><div><span class="eyebrow">A tactile fourth-dimensional toybox</span><h1>Elseplane</h1></div><nav><button id="gallery" class="quiet">Gallery</button><button id="journal" class="quiet">Journal <span id="journal-count">0</span></button><button id="settings" class="quiet">Settings</button><button id="help" class="quiet">How to play</button></nav></header>
  <section class="scene-card"><div id="viewport" aria-label="Interactive 4D toy scene"></div>
    <div class="scene-title"><span id="scene-number">Scene 02</span><div><h2 id="scene-name">First Crossing</h2><p id="scene-prompt">What disappears is still there.</p></div></div>
    <aside class="readout"><span>Slice position</span><strong id="w-readout">W&nbsp; 0.00</strong><small id="selection">No toy selected</small></aside>
  </section>
  <section class="controls" aria-label="Scene controls">
    <label class="wide">Move through W <input id="slice" type="range" min="-4" max="4" step="0.01" value="0"></label>
    <label>XW rotate <input id="xw" type="range" min="-3.14" max="3.14" step="0.01" value="0"></label>
    <label>YW rotate <input id="yw" type="range" min="-3.14" max="3.14" step="0.01" value="0"></label>
    <label>ZW rotate <input id="zw" type="range" min="-3.14" max="3.14" step="0.01" value="0"></label>
    <div class="button-row"><button id="pause">Pause</button><button id="undo" class="quiet">Undo</button><button id="redo" class="quiet">Redo</button><button id="step" class="quiet">Step</button><button id="projection" class="quiet">Projection</button><button id="slower">0.5×</button><button id="recover">Return toys</button><button id="reset" class="quiet">Reset</button><button id="shrink" class="quiet">Smaller</button><button id="grow" class="quiet">Larger</button><button id="recolor" class="quiet">Recolor</button><button id="save" class="quiet">Save experiment</button><button id="open" class="quiet">Open saved</button><button id="export" class="quiet">Export</button><label class="import-label">Import<input id="import" type="file" accept="application/json,.elseplane"></label><span class="drawer-label">Toy Drawer</span><button class="toy-add" data-kind="tesseract">Tesseract</button><button class="toy-add" data-kind="hypersphere">Hypersphere</button><button class="toy-add" data-kind="simplex">5-cell</button><button class="toy-add" data-kind="orthoplex">16-cell</button><button class="toy-add" data-kind="duocylinder">Duocylinder</button><button class="toy-add" data-kind="hypertorus">Ring</button></div>
  </section>
</main>
<dialog id="guide"><button data-close class="close" aria-label="Close">×</button><span class="eyebrow">First Crossing</span><h2>Hold what you can see.</h2><p>Drag a toy to throw it. Drag empty space to orbit the camera. The W slider moves your entire three-dimensional slice through the fourth dimension; the rotation sliders tilt that slice through XW, YW, and ZW.</p><p>If a toy vanishes, move W toward its marker or choose <strong>Return toys</strong>.</p></dialog>
<dialog id="gallery-dialog"><button data-close class="close" aria-label="Close">×</button><span class="eyebrow">Eight experiments</span><h2>The Gallery</h2><div class="gallery-grid">${scenes.map((scene, index) => `<button class="scene-choice" data-scene="${scene.id}"><span>${String(index + 1).padStart(2, '0')}</span><strong>${scene.name}</strong><small>${scene.prompt}</small></button>`).join('')}</div></dialog>
<dialog id="journal-dialog"><button data-close class="close" aria-label="Close">×</button><span class="eyebrow">Things you have noticed</span><h2>Discovery Journal</h2><div id="journal-pages"><p>Move a slice or rotate 4D space to begin noticing what ordinary sight leaves out.</p></div></dialog>
<dialog id="settings-dialog"><button data-close class="close" aria-label="Close">×</button><span class="eyebrow">Comfort and access</span><h2>Settings</h2><label class="setting"><input id="reduced-motion" type="checkbox"> Reduce motion</label><label class="setting"><input id="high-contrast" type="checkbox"> High contrast</label><label class="setting"><input id="muted" type="checkbox"> Mute all sound</label><p>Keyboard: ←/→ move through W, Space pauses, R resets, Ctrl/⌘ Z undoes, Shift Ctrl/⌘ Z redoes.</p></dialog>
<dialog id="intro-dialog"><span class="eyebrow">Welcome to Elseplane</span><h2>See less. Understand more.</h2><p>Begin with a short dimensional analogy, or open the full Gallery now. Nothing is permanently locked.</p><div class="intro-actions"><button id="start-intro">Begin Introduction</button><button id="skip-intro" class="quiet">Skip to Gallery</button></div></dialog>
<div id="toast" role="status" aria-live="polite"></div>`;

const sandbox = new Sandbox(document.querySelector('#viewport')!);
const byId = <T extends HTMLElement>(id: string): T => document.querySelector<T>(`#${id}`)!;
const preferences = loadPreferences();
const applyPreferences = (): void => { document.documentElement.classList.toggle('reduced-motion', preferences.reducedMotion); document.documentElement.classList.toggle('high-contrast', preferences.highContrast); savePreferences(preferences); };
const tone = (frequency = 420): void => { if (preferences.muted) return; const AudioContextClass = window.AudioContext ?? (window as typeof window & { webkitAudioContext: typeof AudioContext }).webkitAudioContext; const context = new AudioContextClass(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.frequency.value = frequency; gain.gain.setValueAtTime(.035, context.currentTime); gain.gain.exponentialRampToValueAtTime(.001, context.currentTime + .16); oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + .17); };
const toast = (message: string): void => { byId('toast').textContent = message; byId('toast').classList.add('show'); window.setTimeout(() => byId('toast').classList.remove('show'), 1800); };
const bindRange = (id: string, apply: (value: number) => void): void => byId<HTMLInputElement>(id).addEventListener('input', (event) => apply(Number((event.target as HTMLInputElement).value)));
const discoveries = new Set<string>(preferences.discoveries);
const notice = (): void => { const isNew = !discoveries.has(sandbox.currentScene.id); discoveries.add(sandbox.currentScene.id); preferences.discoveries = [...discoveries]; applyPreferences(); byId('journal-count').textContent = String(discoveries.size); byId('journal-pages').innerHTML = [...discoveries].map((id) => { const scene = scenes.find((item) => item.id === id)!; return `<article><strong>${scene.name}</strong><p>${scene.discovery}</p></article>`; }).join(''); if (isNew) { tone(620); toast('Discovery added to your Journal'); } };
bindRange('slice', (value) => { sandbox.setSlice(value); if (Math.abs(value) > .7) notice(); });
(['xw', 'yw', 'zw'] as const).forEach((id, axis) => bindRange(id, (value) => { sandbox.setRotation(axis, value); if (Math.abs(value) > .35) notice(); }));
byId('pause').addEventListener('click', () => { sandbox.paused = !sandbox.paused; byId('pause').textContent = sandbox.paused ? 'Play' : 'Pause'; });
byId('slower').addEventListener('click', () => { sandbox.timeScale = sandbox.timeScale === 1 ? 0.5 : sandbox.timeScale === 0.5 ? 0.25 : 1; byId('slower').textContent = `${sandbox.timeScale}×`; });
byId('recover').addEventListener('click', () => sandbox.recoverAll());
byId('undo').addEventListener('click', () => sandbox.undo()); byId('redo').addEventListener('click', () => sandbox.redo());
byId('step').addEventListener('click', () => { sandbox.paused = true; byId('pause').textContent = 'Play'; sandbox.stepOnce(); });
byId('projection').addEventListener('click', () => { const active = sandbox.toggleProjection(); byId('projection').textContent = active ? 'Hide projection' : 'Projection'; });
byId('shrink').addEventListener('click', () => sandbox.resizeSelected(.82)); byId('grow').addEventListener('click', () => sandbox.resizeSelected(1.22)); byId('recolor').addEventListener('click', () => sandbox.recolorSelected());
byId('reset').addEventListener('click', () => { const changed = Math.abs(sandbox.sliceW) > .01 || JSON.stringify(sandbox.toys) !== JSON.stringify(sandbox.currentScene.toys); if (changed && !confirm('Reset this Scene and discard unsaved changes?')) return; sandbox.reset(); for (const id of ['slice', 'xw', 'yw', 'zw']) byId<HTMLInputElement>(id).value = '0'; });
byId('save').addEventListener('click', () => { localStorage.setItem('elseplane:saved-experiment', JSON.stringify(sandbox.experiment())); tone(480); toast('Experiment saved on this device'); });
byId('open').addEventListener('click', () => { const raw = localStorage.getItem('elseplane:saved-experiment'); if (!raw) return toast('No saved experiment yet'); try { sandbox.openExperiment(parseExperiment(raw)); toast('Saved experiment opened'); } catch (error) { toast(error instanceof Error ? error.message : 'Could not open experiment'); } });
byId('export').addEventListener('click', () => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([JSON.stringify(sandbox.experiment(), null, 2)], { type: 'application/json' })); link.download = 'elseplane-experiment.elseplane'; link.click(); URL.revokeObjectURL(link.href); toast('Experiment exported'); });
byId<HTMLInputElement>('import').addEventListener('change', async (event) => { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; try { sandbox.openExperiment(parseExperiment(await file.text())); toast('Experiment imported'); } catch (error) { toast(error instanceof Error ? error.message : 'Could not import experiment'); } });
const guide = byId<HTMLDialogElement>('guide'); const gallery = byId<HTMLDialogElement>('gallery-dialog'); const journal = byId<HTMLDialogElement>('journal-dialog'); const settings = byId<HTMLDialogElement>('settings-dialog'); const intro = byId<HTMLDialogElement>('intro-dialog');
byId('help').addEventListener('click', () => guide.showModal()); byId('gallery').addEventListener('click', () => gallery.showModal()); byId('journal').addEventListener('click', () => journal.showModal()); byId('settings').addEventListener('click', () => settings.showModal());
document.querySelectorAll<HTMLButtonElement>('[data-close]').forEach((button) => button.addEventListener('click', () => button.closest('dialog')?.close()));
document.querySelectorAll<HTMLButtonElement>('.scene-choice').forEach((button) => button.addEventListener('click', () => { sandbox.loadScene(button.dataset.scene!); gallery.close(); const index = scenes.indexOf(sandbox.currentScene); byId('scene-number').textContent = `Scene ${String(index + 1).padStart(2, '0')}`; byId('scene-name').textContent = sandbox.currentScene.name; byId('scene-prompt').textContent = sandbox.currentScene.prompt; for (const id of ['slice', 'xw', 'yw', 'zw']) byId<HTMLInputElement>(id).value = '0'; }));
document.querySelectorAll<HTMLButtonElement>('.toy-add').forEach((button) => button.addEventListener('click', () => { sandbox.addToy(button.dataset.kind as Parameters<typeof sandbox.addToy>[0]); if (sandbox.toys.length >= 4) notice(); }));
sandbox.onChange = () => { byId('w-readout').textContent = `W  ${sandbox.sliceW.toFixed(2)}`; const selected = sandbox.selected; byId('selection').textContent = selected ? `${selected.id.replace('-', ' ')} · W ${selected.position[3].toFixed(2)}` : (sandbox.recoverableCount ? `${sandbox.recoverableCount} recoverable` : 'No toy selected'); };
(['reduced-motion', 'high-contrast', 'muted'] as const).forEach((id) => { const input = byId<HTMLInputElement>(id); const key = id === 'reduced-motion' ? 'reducedMotion' : id === 'high-contrast' ? 'highContrast' : 'muted'; input.checked = preferences[key]; input.addEventListener('change', () => { preferences[key] = input.checked; applyPreferences(); }); });
addEventListener('keydown', (event) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'z') { event.preventDefault(); event.shiftKey ? sandbox.redo() : sandbox.undo(); return; } if (event.key === ' ') { event.preventDefault(); byId('pause').click(); } if (event.key.toLowerCase() === 'r') byId('reset').click(); if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') { const input = byId<HTMLInputElement>('slice'); const value = Math.max(-4, Math.min(4, Number(input.value) + (event.key === 'ArrowRight' ? .1 : -.1))); input.value = String(value); sandbox.setSlice(value); } });
applyPreferences(); if (discoveries.size) notice();
if (!preferences.introductionComplete) intro.showModal();
byId('start-intro').addEventListener('click', () => { preferences.introductionComplete = true; applyPreferences(); sandbox.loadScene('paper-window'); byId('scene-number').textContent = 'Scene 01'; byId('scene-name').textContent = 'Paper Window'; byId('scene-prompt').textContent = scenes[0].prompt; intro.close(); });
byId('skip-intro').addEventListener('click', () => { preferences.introductionComplete = true; applyPreferences(); intro.close(); gallery.showModal(); });
